Add friends likes
AhraAvidzba/java-filmorate pull request #3
Opened 2023-04-01 15:34 UTC by AhraAvidzba

2023-04-01 21:03 UTC, TomattmanYandex requested changes
комменты в файлах

2023-04-01 21:03 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        checkFilmId(filmId);
смотри у тебя два раза будет вызываться получение из базы фильма, это не критично, но когда система работает медленно тогда начинается оптимизация, и вот там придётся это исправлять
лучше получить обьект а потом проверить Null ли он и если не null то использовать
(Ведь мы же считаем что система чаще работает правильно чем неправильно)

2023-04-01 21:03 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmStorage getFilmStorage() {
а вот это выпилить

2023-04-01 21:03 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService {
тут тоже примерно одинаковое будет

2023-04-01 21:03 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService {
что и в предыдущем

2023-04-01 21:03 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (user.getName() == null || user.getName().isEmpty()) {
это логика сервиса

2023-04-02 15:50 UTC, AhraAvidzba commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> findAll(@RequestParam(defaultValue = "10") Integer count) {
Насчет замечания сделать параметр count необязательным. На сколько я понял из дополнительных материалов предоставленных в теории курса при использовании атрибута defaultValue, значение required автоматически устанавливается в false https://www.baeldung.com/spring-request-param

2023-04-03 14:16 UTC, TomattmanYandex approved these changes
Принято, но некоторые моменты лучше переделать к следующему сзаданию

2023-04-03 14:16 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionApiHandler.java
> +        return Map.of("message", exception.getMessage());
Вариант еще лучше, сделать класс модель для сообщений об ошибке, и заполнять его

2023-04-04 09:03 UTC, merged