Add database
AhraAvidzba/java-filmorate pull request #5
Opened 2023-04-29 18:41 UTC by AhraAvidzba

2023-04-30 16:25 UTC, TomattmanYandex requested changes
Работа хорошая, коменты в коде

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DbFilmDao.java
> +        String sql = "SELECT f.*, g.name AS genre_name, g.genre_id, l.user_id AS liked_user " +
очень сложно и непонятно, особенно логика преобразования из результата в обьекты
Вариант как поправить:
получить все фильмы с джойном рейтинга
собрать все их id и сделать запрос на получения filmid, genreid, genre name из трех таблиц с джойнами и в преобразовании в обьекты, раскидать по получным в первом запросе фильмам,
и так же сделять для лайков

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DbFilmDao.java
> +        String sql = "SELECT f.*, g.name AS genre_name, g.genre_id, l.user_id AS liked_user " +
а еще чоень странно смотрится что основной запрос идет к таблице filmGenre

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DbFilmDao.java
> +        if (film.getGenres() == null) {
в апдейте фильмов мы не должны иметь возможность поменять лайки, только жанры рейтинг и поля самого фильма

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DbFilmDao.java
> +        fillLikes(film, film.getId());
тут тоже лайки не особо нужны,

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DbFilmDao.java
> +        String sql3 = "DELETE FROM film_genre WHERE film_id = ?";
обновление жанров можно вынести в отдельный метод целиком, с удалением старых жанров и добавлением новых, все равно эта операция одинакова везде

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DbFilmDao.java
> +    private void fillGenres(Film film, Long filmId) {
почему бы не сделать чтобы этот метод принимал Id фильма и список жанров, это все что ему надо, и уже сразу все делать с этими данными, удалял старые записи и добавлял новые

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DbFilmDao.java
> +    private void fillLikes(Film film, Long filmId) {
а этот метод можно выпилисть, кажется по условию работа с лайками долна быть на получение, а изменение их в рамказх двух других эндпоинтов

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DbFilmDao.java
> +        Map<Long, Set<Long>> likes = new HashMap<>();
уже писал, очень сложная логика лучше упростить, сделать в два или три запроса, чтобы упростить маппинг

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DbGenreDao.java
> +        return jdbcTemplate.queryForObject(sql, (rs, rowNum) -> new Genre(rs.getLong("genre_id"),
даже если только в одном месте используется какой либо функционал, то просто ради читаемости стоит его вынести в отдельный метод, например тут есть два действия, сделать запрос и преобразовать ответ, если второе действие вынести в отдельный метод то
1) читаться и понимать будет легче
2) при добавлении новых методов можно будет пере использовать этот метод
а вообще тут как раз таки дублирование кода,

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DbRatingDao.java
> +        return jdbcTemplate.queryForObject(sql, (rs, rowNum) -> new Rating(Ratings.getIdByRating(Ratings.valueOf(rs.getString("rating"))),
и тут

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DbUserDao.java
> +    public void addToFriendsList(Long userId, Long friendId) {
обычно такое делают на уровне сервиса,
1) првоерили существует ли в базе уже такие данные, 
2) если существуют либо кинули ошибку либо ничего не сделали, если не существует то добавили запись изменили статус старой

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DbUserDao.java
> +    public void delFromFriendsList(Long userId, Long friendId) {
аналогично

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DbUserDao.java
> +    private Map<Long, Status> makeFriendList(Long userId) throws SQLException {
методы которые make делает из резалт сета обьекты, тут лучше переименовать чтобы было консистентно

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Rating.java
> +    Integer id;
модификаторы доступа

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/enums/Genres.java
> +public enum Genres {
этот класс явно лишний, он взаимоисключающий с таблицей жанров
таблица позволяет делать список жанров расширяющимся, т.е. нудно добавить жанр, мы его добавляем в базе и сразу используем, енам мы не можем изменить без того чтобы залазить в код и не перезаливать проект
Поэтому этот класс стоит удалить

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/enums/Ratings.java
> +public enum Ratings {
аналогично с предыдущим

2023-04-30 16:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Autowired
можно воспользоваться аннотацией @RequiredArgsConstructor

2023-04-30 16:25 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +public class FilmorateApplicationTests {
стоить сделать два тестовых класса  один для одного хранилища второй для другого и тестировать все отдельно

2023-04-30 16:25 UTC, TomattmanYandex commented on src/test/resourses/schema.sql
> +CREATE TABLE IF NOT EXISTS film
не поянтно зачем этот файл, обычно тесты смотрят на тестовую папку ресурсов, и если не находят нужный файл в ней, смотрят на основную
а если схема базы отличается в тесах и основном проекте, то это скорее всего проблема

2023-05-01 10:24 UTC, AhraAvidzba commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DbFilmDao.java
> +        String sql = "SELECT f.*, g.name AS genre_name, g.genre_id, l.user_id AS liked_user " +
вообще изначально я так и сделал, для получения фильмов нужно было обратиться к БД 3 раза, но насмотревшись видосов что лучше минимизировать запросы к БД решил поменять на более сложную логику преобразования в объект но с 1 запросом к БД. Согласен, что получилось монструозно, поменяю логику )

2023-05-01 20:53 UTC, AhraAvidzba commented on src/main/resources/schema.sql
> +    status    varchar(13) NOT NULL CHECK (status IN ('CONFIRMED', 'UNCONFIRMED')),
У меня хранение дружбы реализовано так, что этот статус указывает на взаимность дружбы. Инверсированные строки с дружбой двух пользователей не хранятся. То есть можно было сделать реализацию так: если пользователи с id 1 и 2 дружат то можно в таблице из 2х столбцов прописать строки {1, 2;   2,1} я выбрал другой способ, хранится только 1 строка но со статусом указывающим на взаимность дружбы.

2023-05-01 20:55 UTC, AhraAvidzba commented on README.md
>  ![ER-диаграмма](src/main/resources/static/ER-diagram.png)
у меня на гитхабе картинка отображается, она находилась в подпапке static. Сейчас переместил в корень папки resources

2023-05-01 21:47 UTC, AhraAvidzba commented on src/main/java/ru/yandex/practicum/filmorate/dao/Impl/DbFilmDao.java
> +        String sql3 = "DELETE FROM film_genre WHERE film_id = ?";
при добавлении нового фильма я не удаляю старые жанры, получается их удаление выполняется только в одном месте в 3 строчки при обновлении фильма, действительно ли нужно его выносить в отдельный метод? Мне кажется сложнее читаться будет.

2023-05-02 18:00 UTC, TomattmanYandex approved these changes
Принято

2023-05-09 15:54 UTC, merged